# Makefile for the AW_Lib
#
# @author Marcelo Coraça de Freitas <marcelo.batera@gmail.com> 



VERSION=1.0

ifeq ($(OS), Windows_NT)
	OS_DIR=src-windows
else
	OS_DIR=src-linux
endif

ifndef ($(PREFIX))
	PREFIX=/usr/local
endif

ifndef ($(INCLUDE_PREFIX))
	INCLUDE_PREFIX=$(PREFIX)/include/kowlib
endif

ifndef ($(LIB_PREFIX))
	LIB_PREFIX=$(PREFIX)/lib
endif
ifndef ($(GPR_PREFIX)) 
	GPR_PREFIX=$(LIB_PREFIX)/gnat 
endif


projectFile="kowlib.gpr"



all: libs 


libs:
	gnatmake -P ${projectFile}



clean: 
	@gnatclean -P ${projectFile}
	@echo "All clean"

docs:
	@-./gendoc.sh
	@echo "The documentation is generated by a bash script. Then it might fail in other platforms"

gprfile:
	@echo "Preparing GPR file.."
	@echo version:=\"$(VERSION)\" > gpr/kowlib.def
	@echo prefix:=\"$(PREFIX)\" >> gpr/kowlib.def
	@echo lib_prefix:=\"$(LIB_PREFIX)\" >> gpr/kowlib.def
	@echo include_prefix:=\"$(INCLUDE_PREFIX)\" >> gpr/kowlib.def
	@gnatprep gpr/kowlib.gpr.in gpr/kowlib.gpr gpr/kowlib.def

gprclean:
	@rm -f gpr/*gpr
	@rm -f gpr/*.def


install: gprfile
	@echo "Installing files"
	install -d $(INCLUDE_PREFIX)
	install -d $(LIB_PREFIX)
	install -d $(GPR_PREFIX)
	install src/* $(OS_DIR)/* -t $(INCLUDE_PREFIX)
	install lib/* -t $(LIB_PREFIX)
	install gpr/*.gpr -t $(GPR_PREFIX)
	make gprclean
