# Makefile for the AW_Lib
#
# @author Marcelo Coraça de Freitas <marcelo.batera@gmail.com> 


libs:
	gnatmake -P awlib.gpr
tests: libs
	gnatmake -P awlib-tests.gpr

all: libs



clean:
	@rm {bin,lib,obj{,-samples}}/*
	@echo "All clean"



docs:
	@-./gendoc.sh
	@echo "The documentation is generated by a bash script. Then it might fail in other platforms"
